[package]
name = "owl-panda"
version = "0.1.0"
edition = "2021"

[dependencies]
getopts = "0.2.21"
image = { version = "0.25.5", default-features = false, features = ["png"] }
phf = { version = "0.11.2", features = ["macros"] }
